### ISSUE TITLE
mld files are not rendered

### ISSUE THREAD

**Issue by dbuenzli** [OCamlPro/digodoc#33]
It seems these files are currently not rendered. That's a problem for my libraries which often have such files.

Also it would be nice to honour the [`odig` convention](https://erratique.ch/software/odig/doc/packaging.html#odoc_api_and_manual) which allows packages to customize part of the package page landing page via the `index.mld` file of the package. In my packages these files also have important bits for end-users (see e.g. odig's [brr](https://b0-system.github.io/odig/doc/brr/index.html)'s package page).

**Comment by zapashcanon** [comment]
@dbuenzli this is now fixed, please open new issues if you find something is wrong with the rendering. :)

**Comment by dbuenzli** [comment]
Thanks !
