### ISSUE TITLE
Fix links in HTML code in MD files

### ISSUE THREAD

**Issue by RadioPotin** [OCamlPro/digodoc#57]
HTML code found in Markdown files isn't patched when generating sources and fixing static links.

Example:
[Alcotest README.md file](https://github.com/mirage/alcotest/blob/master/README.md)

```markdown
### Examples

A simple example (taken from `examples/simple.ml`):

<p align="center"><img src="./.meta/ok.png" width="65%"></p>
```

This static link won't be patched and rendered in digodoc's Sources tab

**Comment by zapashcanon** [comment]
Fixed in #60.
